### ISSUE TITLE
visualize pipeline failed on macOS

### ISSUE THREAD

**Issue by dragonyanglong** [xpdAcq/streamz_ext#2]
When try to visualize the pipeline built by streaz_ext package: for example `tof_source.visualize('../total_mystream.png', source_node=True)`.
It will have errors as following:
```
Traceback (most recent call last):
  File "/Users/Dragon/Documents/Billinge/dev/sidewinder-spec/sidewinder_spec/nomad/parser.py", line 147, in <module>
    from nomad.pipeline import source, filename_name_nodes
  File "/Users/Dragon/Documents/Billinge/dev/nomad/nomad/pipeline.py", line 5, in <module>
    from nomad.raw_pipeline import (length_source, tth_source, composition,
  File "/Users/Dragon/Documents/Billinge/dev/nomad/nomad/raw_pipeline.py", line 45, in <module>
    tof_source.visualize('../total_mystream.png')
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/streamz_ext/core.py", line 370, in visualize
    return visualize(self, filename, source_node=source_node, **kwargs)
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/streamz/graph.py", line 140, in visualize
    data = g.pipe(format=format)
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/graphviz/files.py", line 96, in pipe
    data = text_type(self.source).encode(self._encoding)
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/graphviz/dot.py", line 91, in __str__
    return '\n'.join(self)
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/graphviz/dot.py", line 82, in __iter__
    yield '\t%s%s' % (kw, self.attributes(None, attr))
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/graphviz/lang.py", line 95, in attributes
    for k, v in tools.mapping_items(kwargs) if v is not None]
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/graphviz/lang.py", line 95, in <listcomp>
    for k, v in tools.mapping_items(kwargs) if v is not None]
  File "/Users/Dragon/anaconda/envs/pipelinePy3/lib/python3.6/site-packages/graphviz/lang.py", line 44, in quote
    if html(identifier):
TypeError: expected string or bytes-like object
```

Package used:
```
graphviz                  2.38.0                        7    conda-forge
graphviz                  0.5.1                     <pip>
pygraphviz                1.3.1                     <pip>
```

**Comment by dragonyanglong** [comment]
I also tried to keep the package graphviz build number (6) exactly the same as Chris:
```
graphviz                  2.38.0                        6    conda-forge
graphviz                  0.5.1                     <pip>
pygraphviz                1.3.1                     <pip>
```
But still failed.
