### ISSUE TITLE
cannot import ``plot_network`` from grave

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/streamz_ext#23]
@CJ-Wright ... making progress, but now cannot import ``plot_network`` from grave

grave is installed 
```
$ python live_plot.py
Traceback (most recent call last):
  File "live_plot.py", line 2, in <module>
    from streamz_ext.graph import node_style, run_vis
  File "c:\users\simon\dev\streamz_ext\streamz_ext\graph.py", line 5, in <module>
    from grave import plot_network
ImportError: cannot import name 'plot_network'
```

**Comment by CJ-Wright** [comment]
How did you install grave?

**Comment by sbillinge** [comment]
whoops, comment in the wrong place.  I think it was ``conda`` from ``conda-forge``

**Comment by CJ-Wright** [comment]
I don't think grave is on conda forge. I think you will need to install it from source.

**Comment by sbillinge** [comment]
mmm, still didn't work, same message.  I restarted the conda env too just to check and no luck.

Here is the install:
```
(bg)
simon@LAPTOP-FU6OME5O MINGW64 ~/dev/grave (master)
$ python setup.py install
running install
running bdist_egg
running egg_info
creating grave.egg-info
writing dependency_links to grave.egg-info\dependency_links.txt
writing grave.egg-info\PKG-INFO
writing top-level names to grave.egg-info\top_level.txt
writing manifest file 'grave.egg-info\SOURCES.txt'
reading manifest file 'grave.egg-info\SOURCES.txt'
writing manifest file 'grave.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\grave
copying grave\grave.py -> build\lib\grave
copying grave\style.py -> build\lib\grave
copying grave\_layout.py -> build\lib\grave
copying grave\_nx_pylab.py -> build\lib\grave
copying grave\__init__.py -> build\lib\grave
creating build\lib\grave\tests
copying grave\tests\conftest.py -> build\lib\grave\tests
copying grave\tests\test_grave.py -> build\lib\grave\tests
copying grave\tests\test_style.py -> build\lib\grave\tests
copying grave\tests\__init__.py -> build\lib\grave\tests
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\grave
copying build\lib\grave\grave.py -> build\bdist.win-amd64\egg\grave
copying build\lib\grave\style.py -> build\bdist.win-amd64\egg\grave
creating build\bdist.win-amd64\egg\grave\tests
copying build\lib\grave\tests\conftest.py -> build\bdist.win-amd64\egg\grave\tests
copying build\lib\grave\tests\test_grave.py -> build\bdist.win-amd64\egg\grave\tests
copying build\lib\grave\tests\test_style.py -> build\bdist.win-amd64\egg\grave\tests
copying build\lib\grave\tests\__init__.py -> build\bdist.win-amd64\egg\grave\tests
copying build\lib\grave\_layout.py -> build\bdist.win-amd64\egg\grave
copying build\lib\grave\_nx_pylab.py -> build\bdist.win-amd64\egg\grave
copying build\lib\grave\__init__.py -> build\bdist.win-amd64\egg\grave
byte-compiling build\bdist.win-amd64\egg\grave\grave.py to grave.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\style.py to style.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\tests\conftest.py to conftest.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\tests\test_grave.py to test_grave.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\tests\test_style.py to test_style.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\tests\__init__.py to __init__.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\_layout.py to _layout.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\_nx_pylab.py to _nx_pylab.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\grave\__init__.py to __init__.cpython-35.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying grave.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying grave.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying grave.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying grave.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying grave.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\grave-0.1-py3.5.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing grave-0.1-py3.5.egg
creating c:\users\simon\anaconda3\envs\bg\lib\site-packages\grave-0.1-py3.5.egg
Extracting grave-0.1-py3.5.egg to c:\users\simon\anaconda3\envs\bg\lib\site-packages
Adding grave 0.1 to easy-install.pth file

Installed c:\users\simon\anaconda3\envs\bg\lib\site-packages\grave-0.1-py3.5.egg
Processing dependencies for grave==0.1
Finished processing dependencies for grave==0.1
C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
```

**Comment by CJ-Wright** [comment]
This needed an install from master
